export type StringDoaGddGA = string;
export interface ObjectOfStringDoaGddGAStringDoaGddGAKieCSt44 {
  name: StringDoaGddGA;
  summary?: StringDoaGddGA;
  [k: string]: any;
}
export type UnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAKieCSt44UIuKSje3 = ObjectOfStringDoaGddGAStringDoaGddGAKieCSt44[];
export interface ObjectOfStringDoaGddGAStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAKieCSt44UIuKSje3U7AKQies {
  name?: StringDoaGddGA;
  version?: StringDoaGddGA;
  environments: UnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAKieCSt44UIuKSje3;
  [k: string]: any;
}
export type StringVp8AIgHF = "active" | "available" | "installed";
export interface ObjectOfStringDoaGddGAStringVp8AIgHFStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAKieCSt44UIuKSje3YY1BLmC3 {
  name?: StringDoaGddGA;
  version?: StringDoaGddGA;
  environments: UnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAKieCSt44UIuKSje3;
  state?: StringVp8AIgHF;
  [k: string]: any;
}
export interface ObjectOfStringDoaGddGAStringDoaGddGACmBlIq6J {
  name?: StringDoaGddGA;
  version?: StringDoaGddGA;
  [k: string]: any;
}
export type UnorderedSetOfStringDoaGddGADvj0XlFa = StringDoaGddGA[];
export interface ObjectOfStringDoaGddGAUnorderedSetOfStringDoaGddGADvj0XlFaZX45Ehh9 {
  cmd: StringDoaGddGA;
  args: UnorderedSetOfStringDoaGddGADvj0XlFa;
  [k: string]: any;
}
export type UnorderedSetOfObjectOfStringDoaGddGAUnorderedSetOfStringDoaGddGADvj0XlFaZX45Ehh9Rf17ZTlR = ObjectOfStringDoaGddGAUnorderedSetOfStringDoaGddGADvj0XlFaZX45Ehh9[];
export interface ObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAUnorderedSetOfStringDoaGddGADvj0XlFaZX45Ehh9Rf17ZTlRF5R1Qy8G {
  setup: UnorderedSetOfObjectOfStringDoaGddGAUnorderedSetOfStringDoaGddGADvj0XlFaZX45Ehh9Rf17ZTlR;
  start: StringDoaGddGA;
  stop: StringDoaGddGA;
  teardown: StringDoaGddGA;
  [k: string]: any;
}
export interface ObjectOfUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaMWFrq3Uy {
  start: UnorderedSetOfStringDoaGddGADvj0XlFa;
  stop: UnorderedSetOfStringDoaGddGADvj0XlFa;
  teardown: UnorderedSetOfStringDoaGddGADvj0XlFa;
  [k: string]: any;
}
/**
 *
 * An object that describes an instance of a service
 *
 */
export interface ObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAUnorderedSetOfStringDoaGddGADvj0XlFaZX45Ehh9Rf17ZTlRF5R1Qy8GObjectOfUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaMWFrq3Uy6Aw04EI2 {
  env: StringDoaGddGA;
  rpcPort: StringDoaGddGA;
  name: StringDoaGddGA;
  version: StringDoaGddGA;
  path: StringDoaGddGA;
  commands: ObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAUnorderedSetOfStringDoaGddGADvj0XlFaZX45Ehh9Rf17ZTlRF5R1Qy8G;
  args: ObjectOfUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaMWFrq3Uy;
  state?: StringDoaGddGA;
  [k: string]: any;
}
export type StringTxhU5DjS = "all" | "running" | "available" | "installed";
export type BooleanVyG3AETh = boolean;
export type UnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAKieCSt44UIuKSje3U7AKQiesYaFk1VHL = ObjectOfStringDoaGddGAStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAKieCSt44UIuKSje3U7AKQies[];
export type UnorderedSetOfObjectOfStringDoaGddGAStringVp8AIgHFStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAKieCSt44UIuKSje3YY1BLmC3Zq6QC3T0 = ObjectOfStringDoaGddGAStringVp8AIgHFStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAKieCSt44UIuKSje3YY1BLmC3[];
export type UnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGACmBlIq6JBb6CmGaX = ObjectOfStringDoaGddGAStringDoaGddGACmBlIq6J[];
export type UnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAUnorderedSetOfStringDoaGddGADvj0XlFaZX45Ehh9Rf17ZTlRF5R1Qy8GObjectOfUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaMWFrq3Uy6Aw04EI22VmgfxII = ObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAUnorderedSetOfStringDoaGddGADvj0XlFaZX45Ehh9Rf17ZTlRF5R1Qy8GObjectOfUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaMWFrq3Uy6Aw04EI2[];
/**
 *
 * Generated! Represents an alias to any of the provided schemas
 *
 */
export type AnyOfStringDoaGddGAStringDoaGddGAStringTxhU5DjSStringDoaGddGAStringDoaGddGAStringDoaGddGABooleanVyG3AEThUnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAKieCSt44UIuKSje3U7AKQiesYaFk1VHLUnorderedSetOfObjectOfStringDoaGddGAStringVp8AIgHFStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAKieCSt44UIuKSje3YY1BLmC3Zq6QC3T0UnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGACmBlIq6JBb6CmGaXUnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAUnorderedSetOfStringDoaGddGADvj0XlFaZX45Ehh9Rf17ZTlRF5R1Qy8GObjectOfUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaMWFrq3Uy6Aw04EI22VmgfxIIObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAUnorderedSetOfStringDoaGddGADvj0XlFaZX45Ehh9Rf17ZTlRF5R1Qy8GObjectOfUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaMWFrq3Uy6Aw04EI2 = StringDoaGddGA | StringTxhU5DjS | BooleanVyG3AETh | UnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAKieCSt44UIuKSje3U7AKQiesYaFk1VHL | UnorderedSetOfObjectOfStringDoaGddGAStringVp8AIgHFStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAKieCSt44UIuKSje3YY1BLmC3Zq6QC3T0 | UnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGACmBlIq6JBb6CmGaX | UnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAUnorderedSetOfStringDoaGddGADvj0XlFaZX45Ehh9Rf17ZTlRF5R1Qy8GObjectOfUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaMWFrq3Uy6Aw04EI22VmgfxII | ObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAUnorderedSetOfStringDoaGddGADvj0XlFaZX45Ehh9Rf17ZTlRF5R1Qy8GObjectOfUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaMWFrq3Uy6Aw04EI2;
export type InstallService = (serviceName: StringDoaGddGA, version: StringDoaGddGA) => Promise<BooleanVyG3AETh>;
export type ListAvailableServices = () => Promise<UnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAKieCSt44UIuKSje3U7AKQiesYaFk1VHL>;
export type ListServices = (filter: StringTxhU5DjS) => Promise<UnorderedSetOfObjectOfStringDoaGddGAStringVp8AIgHFStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAKieCSt44UIuKSje3YY1BLmC3Zq6QC3T0>;
export type ListInstalledServices = () => Promise<UnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGACmBlIq6JBb6CmGaX>;
export type ListRunningServices = () => Promise<UnorderedSetOfObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAUnorderedSetOfStringDoaGddGADvj0XlFaZX45Ehh9Rf17ZTlRF5R1Qy8GObjectOfUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaMWFrq3Uy6Aw04EI22VmgfxII>;
export type StartService = (name: StringDoaGddGA, version: StringDoaGddGA, environment: StringDoaGddGA) => Promise<ObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAStringDoaGddGAObjectOfStringDoaGddGAStringDoaGddGAStringDoaGddGAUnorderedSetOfObjectOfStringDoaGddGAUnorderedSetOfStringDoaGddGADvj0XlFaZX45Ehh9Rf17ZTlRF5R1Qy8GObjectOfUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaUnorderedSetOfStringDoaGddGADvj0XlFaMWFrq3Uy6Aw04EI2>;